$mach_quant = 4

Vagrant.configure("2") do |config|
 
  
  config.vm.provider "virtualbox" do |vb|
      #vb.gui = false
      #vb.memory=256
      #vb.cpus=1
      #vb.check_guest_additions=false
  #config.vm.box_check_update=false
  config.vm.box="ubuntu/focal64"
 end

(1..$mach_quant).each do |i|
    config.vm.define "ansible#{i}" do |node|
        node.vm.network "public_network",
          use_dhcp_assigned_default_route: true
        node.vm.hostname = "ansible#{i}"
    end
end
  
end 