
Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/focal64"
   config.vm.provision "shell", path: "scripts/update_upgrade_mc_ansible.sh"
   $script = <<-SCRIPT
    apt install -y software-properties-common
    apt-add-repository --yes --update ppa:ansible/ansible
    apt install ansible
  SCRIPT
end